### ISSUE TITLE
may we port lovely ValidateHLTMenu to AlCa repo ?

### ISSUE THREAD

**Issue by franzoni** [mmusich/AlCa#1]
hi @tocheng ,
ValidateHLTMenu is a powerful tool;
why don't you place a pull request to release it in to the AlCa/Db repo

here you go: https://github.com/cms-AlCaDB/AlCaTools

thanks thanks!

**Comment by mmusich** [comment]
Done in https://github.com/cms-AlCaDB/AlCaTools/commit/b73f22d0d91f76e313148d2b374e606e178a28a8. 
Closing
